name: build

on:
  push:
  pull_request:

jobs:
  Linux:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        build_type:
          - debug
          - release
        compiler:
          - gcc
          - clang
        arch:
          - x86
          - x64

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: ocornut/imgui
          path: imgui

      - name: Dependencies
        run: sudo apt-get install g++-multilib

      - name: Configure
        run: cmake -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -DCMAKE_C_COMPILER=${{ matrix.compiler }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DGCC_ARCH=${{ matrix.arch }} -B cmake-build -S .github

      - name: Build
        run: cmake --build cmake-build --parallel $(nproc)


  MacOS:
    runs-on: macos-11

    strategy:
      fail-fast: false
      matrix:
        build_type:
          - debug
          - release
        arch:
          - x86
          - x64

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: ocornut/imgui
          path: imgui

      - name: Configure
        shell: bash
        run: cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DGCC_ARCH=${{ matrix.arch }} -B cmake-build -S .github

      - name: Build
        shell: bash
        run: cmake --build cmake-build --parallel $(sysctl -n hw.ncpu)

  Windows:
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        build_type:
          - debug
          - release
        arch:
          - Win32
          - x64
        compiler:
          - msvc
          - mingw

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: ocornut/imgui
          path: imgui

      - name: Configure (MSVC)
        if: matrix.compiler == 'msvc'
        shell: bash
        run: cmake -G 'Visual Studio 17 2022' -A ${{ matrix.arch }} -B cmake-build -S .github

      - name: Build (MSVC)
        if: matrix.compiler == 'msvc'
        shell: bash
        run: cmake --build cmake-build -- -p:Configuration=${{ matrix.build_type }} -maxcpucount:$NUMBER_OF_PROCESSORS

      - name: Configure (MingW)
        if: matrix.compiler == 'mingw'
        shell: bash
        run: cmake -G 'MinGW Makefiles' -DGCC_ARCH=${{ matrix.arch }} -B cmake-build -S .github

      - name: Build (MingW)
        if: matrix.compiler == 'mingw'
        shell: bash
        run: cmake --build cmake-build --parallel $NUMBER_OF_PROCESSORS
